__game_font_styles =
{
	Help = T{984, --[[Help]] "SchemeBk, 15, aa"},
	HelpHint = T{986, --[[HelpHint]] "SchemeBk, 16, aa"},

	PopupTitle = T{8572, --[[PopupTitle]] "LibelSuitRg, 30, aa"},
	PopupDescr = T{8573, --[[PopupDescr]] "SchemeBk, 18, aa"},
	HexChoice = T{8574, --[[HexChoice]] "SchemeBk, 16, aa"},
	
	RolloverTitle = T{8575, --[[HexChoice]] "LibelSuitRg, 22, aa"},
	RolloverText = T{8576, --[[HexChoice]] "SchemeBk, 18, aa"},
	RolloverHint = T{990, --[[HexChoice]] "SchemeBk, 18, aa"},
	
	BuildMenuBuilding = T{991, --[[BuildMenuBuilding]] "LibelSuitRg, 23, aa"},
	BuildMenuCategory = T{989, --[[BuildMenuCategory]] "LibelSuitRg, 20, aa"},
	
	FarmCropLine = T{992, --[[FarmCropLine]] "SchemeBk, 20, aa"},
	InfopanelTitle = T{7638, --[[InfopanelTitle]] "LibelSuitRg, 22, aa"},
	InfopanelSectionTitle = T{993, --[[InfopanelTitle]] "LibelSuitRg, 22, aa"},
	InfopanelText = T{994, --[[InfopanelText]] "SchemeBk, 18, aa"},
	
	HUDSol = T{9762, --[[HUDSol]] "SchemeBk, 18, aa"},
	HUDHumans = T{992, --[[HUDHumans]] "SchemeBk, 20, aa"},
	HUDDrones = T{992, --[[HUDDrones]] "SchemeBk, 20, aa"},
	HUDConstruction = T{995, --[[HUDHumans]] "LibelSuitRg, 26, aa"},
	HUDButton = T{995, --[[HUDHumans]] "LibelSuitRg, 26, aa"},
	
	OnScreenTitle = T{989, --[[OnScreenTitle]] "LibelSuitRg, 20, aa"},
	OnScreenText = T{988, --[[OnScreenText]] "SchemeBk, 16, aa"},
	
	PinTextSmall = T{988, --[[PinTextSmall]] "SchemeBk, 16, aa"},
	PinText      = T{994, --[[PinText]] "SchemeBk, 18, aa"},
	PinButton    = T{996, --[[PinButton]] "SchemeBk, 12, aa"},
	PinButtonBig = T{997, --[[PinButtonBig]] "SchemeBk, 15, aa"},
	PinButtonSmall = T{998, --[[PinButtonBig]] "SchemeBk, 11, aa"},

	ResearchIconTitle = T{993, --[[ResearchIconTitle]] "LibelSuitRg, 22, aa"},
	ResearchIconTitleBig = T{999, --[[ResearchIconTitleBig]] "LibelSuitRg, 32, aa"},
	ResearchStats = T{992, --[[ResearchStats]] "SchemeBk, 20, aa"},
	ResearchBtn = T{1000, --[[ResearchBtn]] "LibelSuitRg, 24, aa"},
	
	PGChallengeRating = T{995, --[[PGChallengeRating]] "LibelSuitRg, 26, aa"},
	PGLogo = T{987, --[[PGLogo]] "LibelSuitRg, 28, aa"},
	PGListItem = T{995, --[[PGListItem]] "LibelSuitRg, 26, aa"},
	PGMissionDescrTitle = T{1001, --[[PGMissionDescrTitle]] "LibelSuitRg, 30, aa"},
	PGMissionDescr = T{992, --[[PGMissionDescr]] "SchemeBk, 20, aa"},
	PGMissionEffectsHint = T{992, --[[PGMissionEffectsHint]] "SchemeBk, 20, aa"},
	PGResource = T{995, --[[PGResource]] "LibelSuitRg, 26, aa"},
	PGLandingPosDetails = T{995, --[[PGLandingPosDetails]] "LibelSuitRg, 26, aa"},
	PGChallengeSummary = T{993, --[[PGChallengeSummary]] "LibelSuitRg, 22, aa"},
	PGLandingPosName = T{1002, --[[PGLandingPosName]] "LibelSuitRg, 36, aa"},
	PGModDescr = T{992, --[[PGModDescr]] "SchemeBk, 20, aa"},
	PGModTitle = T{1001, --[[PGModTitle]] "LibelSuitRg, 30, aa"},
	PGModAuthorDate = T{9837, --[[PGModAuthorDate]] "LibelSuitRg, 25, aa"},
	PGModTags = T{993, --[[PGModTags]] "LibelSuitRg, 22, aa"},
	PGModWarning = T{1001, --[[PGModWarning]] "LibelSuitRg, 30, aa"},
	PGTags = T{1002, --[[PGTags]] "LibelSuitRg, 36, aa"},
	PGPage = T{995, --[[PGPage]] "LibelSuitRg, 26, aa"},
	
	PreGamePlanetCoordinates = T{1001, --[[PreGamePlanetCoordinates]] "LibelSuitRg, 30, aa"},
	PreGamePlanetCoordinatesHint = T{1004, --[[PreGamePlanetCoordinatesHint]] "LibelSuitRg, 18, aa"},
	
	MarsBigButton = T{1005, --[[MarsBigButton]] "LibelSuitRg, 56, aa"},
	MarsSmallButton = T{1002, --[[MarsSmallButton]] "LibelSuitRg, 36, aa"},
	
	ParadoxAccountItemTitle = T{989, --[[ParadoxAccountItemTitle]] "LibelSuitRg, 20, aa"},
	ParadoxCombo = T{1006, --[[ParadoxCombo]] "SchemeBk, 22, aa"},
	ParadoxEdit = T{1006, --[[ParadoxEdit]] "SchemeBk, 22, aa"},
	
	SaveGameEdit = T{987, --[[SaveGameEdit]] "LibelSuitRg, 28, aa"},
	AutosaveText = T{1002, --[[AutosaveText]] "LibelSuitRg, 36, aa"},
	
	EncyclopediaArticleTitle = T{1001, --[[EncyclopediaArticleTitle]] "LibelSuitRg, 30, aa"},
	EncyclopediaArticleDescr = T{994, --[[EncyclopediaArticleDescr]] "SchemeBk, 18, aa"},
	EncyclopediaSubTitle = T{995, --[[EncyclopediaSubTitle]] "LibelSuitRg, 26, aa"},
	
	Version = T{1004, --[[Version]] "LibelSuitRg, 18, aa"},
	
	MarsMenuItemButton = T{1007, --[[MarsMenuItemButton]] "LibelSuitRg, 39, aa"},
	MarsOptionsKeybind = T{993, --[[MarsOptionsKeybind]] "LibelSuitRg, 22, aa"},
	MarsOptionsKeybindSmall = T{1008, --[[MarsOptionsKeybindSmall]] "LibelSuitRg, 17, aa"},
	
	PhotoModeFilePath = T{9838, --[[PhotoModeFilePath]] "LibelSuitRg, 25, aa"},
	
	UICreditsCompanyName =  T{1005, --[[UICreditsCompanyName]] "LibelSuitRg, 56, aa"},
	UICredits            =  T{1002, --[[UICredits]] "LibelSuitRg, 36, aa"},
	
	GoalsDescription = T{1003, --[[GoalsDescription]] "LibelSuitRg, 24, aa"},
	GoalsReward = T{1003, --[[GoalsDescription]] "LibelSuitRg, 24, aa"},
	
	ModsUIItemTitleConsole = T{9839, --[[ModsUIItemTitleConsole]] "Source Sans Pro, 30, bold, aa"},
	ModsUIItemSubtitleConsole = T{10550, --[[ModsUIItemSubtitleConsole]] "Source Sans Pro, 22, aa"},
	ModsUIItemTitlePC = T{9841, --[[ModsUIItemTitlePC]] "Source Sans Pro, 26, bold, aa"},
	ModsUIItemSubtitlePC = T{9842, --[[ModsUIItemSubtitlePC]] "Source Sans Pro, 18, aa"},
	ModsUIItemStatusConsole = T{9843, --[[ModsUIItemStatusConsole]] "Source Sans Pro, 24, bold, aa"},
	ModsUIItemStatusPC = T{9842, --[[ModsUIItemStatusPC]] "Source Sans Pro, 18, aa"},
	ModsUITab = T{10379, --[[ModsUITab]] "Source Sans Pro, 26, aa"},
	ModsUITabBold = T{9841, --[[ModsUITabBold]] "Source Sans Pro, 26, bold, aa"},
	ModsUIPopupTitle = T{9844, --[[ModsUIPopupTitle]] "Source Sans Pro, 28, aa, bold"},
	ModsUIInfoText = T{9845, --[[ModsUIInfoText]] "Source Sans Pro, 20, aa"},
	ModsUISortText = T{9846, --[[ModsUISortText]] "Source Sans Pro, 20, bold, aa"},
	ModsUISearch = T{9847, --[[ModsUISearch]] "Source Sans Pro, 18, italic, aa"},
	ModsUIInstalledCount = T{9842, --[[ModsUIInstalledCount]] "Source Sans Pro, 18, aa"},
	ModsUIInstallPC = T{9848, --[[ModsUIInstallPC]] "Source Sans Pro, 14, aa"},
	ModsUIInstallPCBold = T{9849, --[[ModsUIInstallPC]] "Source Sans Pro, 14, bold, aa"},
	ModsUIAction = T{9840, --[[ModsUIAction]] "Source Sans Pro, 24, aa"},
	ModsUITagsTitle = T{9850, --[[ModsUITagsTitle]] "Source Sans Pro, 16, aa"},
	ModsUIPopupsText= T{9840, --[[ModsUIPopupsText]] "Source Sans Pro, 24, aa"},
	ModsUITag = T{9845, --[[ModsUITag]] "Source Sans Pro, 20, aa"},
	ModsUIDetailsTitle = T{9851, --[[ModsUIDetailsTitle]] "Source Sans Pro, 34, bold, aa"},
	ModsUIDetailsSubtitle = T{9845, --[[ModsUIDetailsSubtitle]] "Source Sans Pro, 20, aa"},
	ModsUIDetailsVersionLabel = T{9850, --[[ModsUIDetailsVersion]] "Source Sans Pro, 16, aa"},
	ModsUIDetailsVersion = T{9842, --[[ModsUIDetailsVersion]] "Source Sans Pro, 18, aa"},
	ModsUIDetailsStatus = T{9843, --[[ModsUIDetailsStatus]] "Source Sans Pro, 24, bold, aa"},
	ModsUIHeading1 = T{9843, "Source Sans Pro, 24, bold, aa" },
	ModsUIHeading2 = T{9846, "Source Sans Pro, 20, bold, aa" },
	ModsUIHeading3 = T{10380, "Source Sans Pro, 16, bold, aa" },
	ModsUILogInTitle = T{10381, --[[ModsUILogInTitle]] "Source Sans Pro, 22, bold, aa"},
	ModsUIRateFlagTitle = T{9841, --[[ModsUIRateFlagTitle]] "Source Sans Pro, 26, bold, aa"},
	ModsUIRateText = T{9840, --[[ModsUIRateText]] "Source Sans Pro, 24, aa"},
	ModsUILogInEdit = T{10382, --[[ModsUILogInEdit]] "Source Sans Pro, 20,  aa"},
	ModsUILogInText = T{9842, --[[ModsUILogInText]] "Source Sans Pro, 18, aa"},
	ModsUILogInButtons = T{9842, --[[ModsUILogInButtons]] "Source Sans Pro, 18, aa"},
	ModsUISignUpRequired = T{9848, --[[ModsUISignUpRequired]] "Source Sans Pro, 14, aa"},
	ModsUISignUpFieldLabel = T{9850, --[[ModsUISignUpFieldLabel]] "Source Sans Pro, 16, aa"},
	ModsUIDescription= T{9845, --[[ModsUIDescription]] "Source Sans Pro, 20, aa"},
	ModsUIDetailsColumnHeadings = T{9842, --[[ModsUIDetailsColumnHeadings]] "Source Sans Pro, 18, aa"},
	ModsUIDetailsColumnItems = T{9846, --[[ModsUIDetailsColumnItems]] "Source Sans Pro, 20, bold, aa"},
	ModsUIDetailsChangelog = T{9845, --[[ModsUIDetailsChangelog]] "Source Sans Pro, 20, aa"},
	ModsUIDetailsDescription = T{10379, --[[ModsUIDetailsDescription]] "Source Sans Pro, 26, aa"},
	ModsUIDetailsRatingsTotal = T{9850, --[[ModsUIDetailsRatingsTotal]] "Source Sans Pro, 16, aa"},
}

TranslateFontStyles(__game_font_styles)