-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

PlaceObj('XTemplate', {
	__is_kind_of = "XLayer",
	group = "Layers",
	id = "GamepadControlsOverview",
	PlaceObj('XTemplateWindow', {
		'__class', "XLayer",
		'HAlign', "center",
		'HandleKeyboard', false,
	}, {
		PlaceObj('XTemplateWindow', {
			'__condition', function (parent, context) return GetUIStyleGamepad() and not ShouldShowPS4Images() end,
			'__class', "XFitContent",
			'IdNode', false,
			'HandleKeyboard', false,
			'HandleMouse', false,
			'Fit', "smallest",
		}, {
			PlaceObj('XTemplateWindow', {
				'Id', "idContent",
				'HAlign', "left",
				'VAlign', "center",
				'MinWidth', 1920,
				'MinHeight', 1080,
				'MaxWidth', 1920,
				'MaxHeight', 1080,
			}, {
				PlaceObj('XTemplateWindow', {
					'__condition', function (parent, context) return not Platform.durango and g_TestUIPlatform ~= "durango" end,
					'__class', "XImage",
					'Image', "UI/DesktopGamepad/Controller.tga",
					'ImageScale', point(800, 800),
				}),
				PlaceObj('XTemplateWindow', {
					'__condition', function (parent, context) return Platform.durango or g_TestUIPlatform == "durango" end,
					'__class', "XImage",
					'Image', "UI/Durango/Controller.tga",
					'ImageScale', point(800, 800),
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "LT",
					'__class', "XText",
					'Margins', box(0, 250, 1115, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4246, --[[XTemplate GamepadControlsOverview Text]] "Game Menu"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "LB",
					'__class', "XText",
					'Margins', box(0, 270, 1205, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4245, --[[XTemplate GamepadControlsOverview Text]] "Notifications<newline>(Hold) Dismiss all notifications<newline>(Build menu) Previous category"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "LS",
					'__class', "XText",
					'Margins', box(0, 395, 1285, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4244, --[[XTemplate GamepadControlsOverview Text]] "Pan view<newline>(press) Cycle Domes"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Back",
					'__class', "XText",
					'Margins', box(0, 785, 1260, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{7584, --[[XTemplate GamepadControlsOverview Text]] "Dismiss hint"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "DPad",
					'__class', "XText",
					'Margins', box(0, 835, 1050, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4243, --[[XTemplate GamepadControlsOverview Text]] "Game speed / Infobar"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "RS",
					'__class', "XText",
					'Margins', box(920, 820, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'MaxWidth', 200,
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4242, --[[XTemplate GamepadControlsOverview Text]] "Rotate / Zoom view<newline>(press) Cycle Rovers"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "RB",
					'__class', "XText",
					'Margins', box(1180, 300, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4236, --[[XTemplate GamepadControlsOverview Text]] "Pins<newline>(Build menu) Next category"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "RT",
					'__class', "XText",
					'Margins', box(1120, 220, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4235, --[[XTemplate GamepadControlsOverview Text]] "Manage Infopanel\n(Hold) Infopanel shortcuts"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Y",
					'__class', "XText",
					'Margins', box(1235, 400, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4237, --[[XTemplate GamepadControlsOverview Text]] "Build Menu"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "X",
					'__class', "XText",
					'Margins', box(1255, 510, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4238, --[[XTemplate GamepadControlsOverview Text]] "Select Drones or Colonists"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "B",
					'__class', "XText",
					'Margins', box(1255, 640, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4239, --[[XTemplate GamepadControlsOverview Text]] "Close / Cancel"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "A",
					'__class', "XText",
					'Margins', box(1240, 750, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4240, --[[XTemplate GamepadControlsOverview Text]] "Select buildings / rovers"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Start",
					'__class', "XText",
					'Margins', box(1180, 835, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4241, --[[XTemplate GamepadControlsOverview Text]] "Main Menu"},
				}),
				}),
			}),
		PlaceObj('XTemplateWindow', {
			'__condition', function (parent, context) return GetUIStyleGamepad() and ShouldShowPS4Images() end,
			'__class', "XFitContent",
			'IdNode', false,
			'HandleKeyboard', false,
			'HandleMouse', false,
			'Fit', "smallest",
		}, {
			PlaceObj('XTemplateWindow', {
				'Id', "idContent",
				'HAlign', "left",
				'VAlign', "center",
				'MinWidth', 1920,
				'MinHeight', 1080,
				'MaxWidth', 1920,
				'MaxHeight', 1080,
			}, {
				PlaceObj('XTemplateWindow', {
					'__condition', function (parent, context) return not Platform.durango end,
					'__class', "XImage",
					'Image', "UI/PS4/Controller.tga",
					'ImageScale', point(800, 800),
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Options",
					'__class', "XText",
					'Margins', box(0, 255, 800, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{1010, --[[XTemplate GamepadControlsOverview Text]] "Main Menu"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Touch",
					'__class', "XText",
					'Margins', box(0, 280, 980, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{7584, --[[XTemplate GamepadControlsOverview Text]] "Dismiss hint"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "L2",
					'__class', "XText",
					'Margins', box(0, 210, 1210, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4246, --[[XTemplate GamepadControlsOverview Text]] "Game Menu"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "L1",
					'__class', "XText",
					'Margins', box(0, 370, 1260, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4245, --[[XTemplate GamepadControlsOverview Text]] "Notifications<newline>(Hold) Dismiss all notifications<newline>(Build menu) Previous category"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "DPad",
					'__class', "XText",
					'Margins', box(0, 610, 1270, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4243, --[[XTemplate GamepadControlsOverview Text]] "Game speed / Infobar"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "LS",
					'__class', "XText",
					'Margins', box(0, 775, 1230, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4244, --[[XTemplate GamepadControlsOverview Text]] "Pan view<newline>(press) Cycle Domes"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "RS",
					'__class', "XText",
					'Margins', box(0, 740, 860, 0),
					'Dock', "box",
					'HAlign', "right",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4242, --[[XTemplate GamepadControlsOverview Text]] "Rotate / Zoom view<newline>(press) Cycle Rovers"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Square",
					'__class', "XText",
					'Margins', box(1180, 800, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4238, --[[XTemplate GamepadControlsOverview Text]] "Select Drones or Colonists"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "X",
					'__class', "XText",
					'Margins', box(1275, 680, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4240, --[[XTemplate GamepadControlsOverview Text]] "Select buildings / rovers"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Circle",
					'__class', "XText",
					'Margins', box(1275, 540, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4239, --[[XTemplate GamepadControlsOverview Text]] "Close / Cancel"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "RB",
					'__class', "XText",
					'Margins', box(1225, 320, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4236, --[[XTemplate GamepadControlsOverview Text]] "Pins<newline>(Build menu) Next category"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "Triangle",
					'__class', "XText",
					'Margins', box(1275, 465, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4237, --[[XTemplate GamepadControlsOverview Text]] "Build Menu"},
				}),
				PlaceObj('XTemplateWindow', {
					'comment', "RT",
					'__class', "XText",
					'Margins', box(1220, 190, 0, 0),
					'Dock', "box",
					'HAlign', "left",
					'VAlign', "top",
					'TextFont', "HUDButton",
					'TextColor', RGBA(255, 255, 255, 255),
					'RolloverTextColor', RGBA(255, 255, 255, 255),
					'ShadowType', "outline",
					'ShadowSize', 1,
					'ShadowColor', RGBA(32, 32, 32, 128),
					'Translate', true,
					'Text', T{4235, --[[XTemplate GamepadControlsOverview Text]] "Manage Infopanel\n(Hold) Infopanel shortcuts"},
				}),
				}),
			}),
		}),
})

