-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

PlaceObj('XTemplate', {
	group = "InGame",
	id = "Infobar",
	PlaceObj('XTemplateWindow', {
		'__class', "Infobar",
		'ZOrder', 150,
		'FocusOnOpen', "",
	}, {
		PlaceObj('XTemplateAction', {
			'ActionId', "close",
			'ActionTranslate', false,
			'ActionShortcut', "Escape",
			'ActionGamepad', "ButtonB",
			'OnAction', function (self, host, source)
host:SetFocus(false, true)
XDestroyRolloverWindow()
end,
		}),
		PlaceObj('XTemplateWindow', {
			'Margins', box(-274, 0, -274, 0),
			'HAlign', "center",
			'VAlign', "top",
		}, {
			PlaceObj('XTemplateWindow', {
				'__context', function (parent, context)  end,
				'__class', "XFrame",
				'Id', "idPad",
				'Padding', box(274, 0, 274, 0),
				'HAlign', "center",
				'VAlign', "top",
				'MaxHeight', 30,
				'LayoutMethod', "HList",
				'HandleMouse', true,
				'Image', "UI/Common/bm_pad.tga",
				'FrameBox', box(274, 109, 274, 3),
				'SqueezeX', false,
				'FlipY', true,
			}, {
				PlaceObj('XTemplateWindow', {
					'__class', "XContextControl",
					'RolloverTemplate', "Rollover",
					'RolloverAnchor', "bottom",
					'RolloverText', T{974796457889, --[[XTemplate Infobar RolloverText]] "<FundingRollover>"},
					'RolloverTitle', T{500807906538, --[[XTemplate Infobar RolloverTitle]] "Funding"},
					'RolloverHintGamepad', T{816190283569, --[[XTemplate Infobar RolloverHintGamepad]] "<DPad> Navigate <DPadDown> Close"},
					'Id', "idFunding",
					'MinWidth', 55,
					'RolloverOnFocus', true,
					'RelativeFocusOrder', "next-in-line",
					'FXMouseIn', "UIButtonMouseIn",
				}, {
					PlaceObj('XTemplateWindow', {
						'__class', "XImage",
						'Id', "idRollover",
						'Dock', "box",
						'Visible', false,
						'Image', "UI/Common/row_shine_2.tga",
						'ImageFit', "stretch",
					}),
					PlaceObj('XTemplateWindow', {
						'__class', "XText",
						'Id', "idFunding",
						'Padding', box(2, 4, 2, 4),
						'HAlign', "center",
						'TextStyle', "Infobar",
						'Translate', true,
						'Text', T{325404562808, --[[XTemplate Infobar Text]] "<FundingText>"},
						'TextHAlign', "center",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateFunc', {
						'name', "OnSetFocus",
						'func', function (self, ...)
XCreateRolloverWindow(self, true)
XText.OnSetFocus(self, ...)
end,
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XContextControl",
					'RolloverTemplate', "Rollover",
					'RolloverAnchor', "bottom",
					'RolloverText', T{113756642387, --[[XTemplate Infobar RolloverText]] "<ResearchRollover>"},
					'RolloverTitle', T{783732441536, --[[XTemplate Infobar RolloverTitle]] "Research"},
					'RolloverHintGamepad', T{816190283569, --[[XTemplate Infobar RolloverHintGamepad]] "<DPad> Navigate <DPadDown> Close"},
					'Id', "idResearch",
					'MinWidth', 130,
					'RolloverOnFocus', true,
					'RelativeFocusOrder', "next-in-line",
					'FXMouseIn', "UIButtonMouseIn",
				}, {
					PlaceObj('XTemplateWindow', {
						'__class', "XImage",
						'Id', "idRollover",
						'Dock', "box",
						'Visible', false,
						'Image', "UI/Common/row_shine_2.tga",
						'ImageFit', "stretch",
					}),
					PlaceObj('XTemplateWindow', {
						'__class', "XText",
						'Id', "idResearch",
						'Padding', box(2, 4, 2, 4),
						'HAlign', "center",
						'TextStyle', "Infobar",
						'Translate', true,
						'Text', T{212300384149, --[[XTemplate Infobar Text]] "<ResearchText>"},
						'TextHAlign', "center",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateFunc', {
						'name', "OnSetFocus",
						'func', function (self, ...)
XCreateRolloverWindow(self, true)
XText.OnSetFocus(self, ...)
end,
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XContextControl",
					'RolloverTemplate', "Rollover",
					'RolloverAnchor', "bottom",
					'RolloverText', T{991234155964, --[[XTemplate Infobar RolloverText]] "<GridResourcesRollover>"},
					'RolloverTitle', T{230396890407, --[[XTemplate Infobar RolloverTitle]] "Grid Resources"},
					'RolloverHintGamepad', T{816190283569, --[[XTemplate Infobar RolloverHintGamepad]] "<DPad> Navigate <DPadDown> Close"},
					'Id', "idGridResources",
					'MinWidth', 185,
					'RolloverOnFocus', true,
					'RelativeFocusOrder', "next-in-line",
					'FXMouseIn', "UIButtonMouseIn",
				}, {
					PlaceObj('XTemplateWindow', {
						'__class', "XImage",
						'Id', "idRollover",
						'Dock', "box",
						'Visible', false,
						'Image', "UI/Common/row_shine_2.tga",
						'ImageFit', "stretch",
					}),
					PlaceObj('XTemplateWindow', {
						'__class', "XText",
						'Id', "idGridResources",
						'Padding', box(2, 4, 2, 4),
						'HAlign', "center",
						'TextStyle', "Infobar",
						'Translate', true,
						'Text', T{374440054184, --[[XTemplate Infobar Text]] "<GridResourcesText>"},
						'TextHAlign', "center",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateFunc', {
						'name', "OnSetFocus",
						'func', function (self, ...)
XCreateRolloverWindow(self, true)
XText.OnSetFocus(self, ...)
end,
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XContextControl",
					'Id', "idBasicResources",
					'MinWidth', 250,
					'RolloverOnFocus', true,
				}, {
					PlaceObj('XTemplateFunc', {
						'name', "OnSetFocus",
						'func', function (self, ...)
XCreateRolloverWindow(self, true)
XContextWindow.OnSetFocus(self, ...)
end,
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "centers the texts",
						'HAlign', "center",
						'LayoutMethod', "HList",
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{965950572237, --[[XTemplate Infobar RolloverText]] "<MetalsRollover>"},
							'RolloverTitle', T{921009833362, --[[XTemplate Infobar RolloverTitle]] "Metals"},
							'RolloverHint', T{185759925809, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{238973917718, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("Metals")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idMetals",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{290848825416, --[[XTemplate Infobar Text]] "<MetalsText>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{777092042856, --[[XTemplate Infobar RolloverText]] "<ConcreteRollover>"},
							'RolloverTitle', T{558957250020, --[[XTemplate Infobar RolloverTitle]] "Concrete"},
							'RolloverHint', T{185759925809, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{868548677390, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("Concrete")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idConcrete",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{563905203540, --[[XTemplate Infobar Text]] "<ConcreteText>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{531540704716, --[[XTemplate Infobar RolloverText]] "<FoodRollover>"},
							'RolloverTitle', T{165513395865, --[[XTemplate Infobar RolloverTitle]] "Food"},
							'RolloverHint', T{185759925809, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{868548677390, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("Food")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idFood",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{587907473693, --[[XTemplate Infobar Text]] "<FoodText>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{101740720498, --[[XTemplate Infobar RolloverText]] "<RareMetalsRollover>"},
							'RolloverTitle', T{421995872564, --[[XTemplate Infobar RolloverTitle]] "Rare Metals"},
							'RolloverHint', T{185759925809, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{868548677390, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("PreciousMetals")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idPreciousMetals",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{118276114882, --[[XTemplate Infobar Text]] "<PreciousMetalsText>"},
							}),
							}),
						}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XContextControl",
					'Id', "idAdvancedResources",
					'MinWidth', 250,
					'RolloverOnFocus', true,
				}, {
					PlaceObj('XTemplateFunc', {
						'name', "OnSetFocus",
						'func', function (self, ...)
XCreateRolloverWindow(self, true)
XContextWindow.OnSetFocus(self, ...)
end,
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "centers the texts",
						'HAlign', "center",
						'LayoutMethod', "HList",
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{353676002560, --[[XTemplate Infobar RolloverText]] "<PolymersRollover>"},
							'RolloverTitle', T{112574648549, --[[XTemplate Infobar RolloverTitle]] "Polymers"},
							'RolloverHint', T{846761005248, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{910237457414, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("Polymers")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idPolymers",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{456271481390, --[[XTemplate Infobar Text]] "<PolymersText>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{400795478220, --[[XTemplate Infobar RolloverText]] "<ElectronicsRollover>"},
							'RolloverTitle', T{406684885664, --[[XTemplate Infobar RolloverTitle]] "Electronics"},
							'RolloverHint', T{846761005248, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{910237457414, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("Electronics")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idElectronics",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{312385745918, --[[XTemplate Infobar Text]] "<ElectronicsText>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{565651032917, --[[XTemplate Infobar RolloverText]] "<MachinePartsRollover>"},
							'RolloverTitle', T{478510455605, --[[XTemplate Infobar RolloverTitle]] "Machine Parts"},
							'RolloverHint', T{846761005248, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{910237457414, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("MachineParts")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idMachineParts",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{411476328157, --[[XTemplate Infobar Text]] "<MachinePartsText>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverTemplate', "Rollover",
							'RolloverAnchor', "bottom",
							'RolloverText', T{632386079741, --[[XTemplate Infobar RolloverText]] "<FuelRollover>"},
							'RolloverTitle', T{627597841939, --[[XTemplate Infobar RolloverTitle]] "Fuel"},
							'RolloverHint', T{846761005248, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
							'RolloverHintGamepad', T{910237457414, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'RelativeFocusOrder', "next-in-line",
							'FXMouseIn', "UIButtonMouseIn",
							'FXPress', "BuildMenuButtonClick",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleResources("Fuel")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XImage",
								'Id', "idRollover",
								'Dock', "box",
								'Visible', false,
								'Image', "UI/Common/row_shine_2.tga",
								'ImageFit', "stretch",
							}),
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idFuel",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{771466895406, --[[XTemplate Infobar Text]] "<FuelText>"},
							}),
							}),
						}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XContextControl",
					'RolloverTemplate', "Rollover",
					'RolloverAnchor', "bottom",
					'RolloverText', T{931628884394, --[[XTemplate Infobar RolloverText]] "<ColonistsRollover>"},
					'RolloverTitle', T{782298266613, --[[XTemplate Infobar RolloverTitle]] "Colonists<right><colonist(ColonistCount)>"},
					'RolloverHint', T{341358393315, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle"},
					'RolloverHintGamepad', T{581577064086, --[[XTemplate Infobar RolloverHintGamepad]] "<DPad> Navigate <DPadDown> Close"},
					'Id', "idColonists",
					'MinWidth', 150,
					'RolloverOnFocus', true,
					'RelativeFocusOrder', "next-in-line",
					'FXMouseIn', "UIButtonMouseIn",
				}, {
					PlaceObj('XTemplateFunc', {
						'name', "OnSetFocus",
						'func', function (self, ...)
XCreateRolloverWindow(self, true)
XContextWindow.OnSetFocus(self, ...)
end,
					}),
					PlaceObj('XTemplateWindow', {
						'__class', "XImage",
						'Id', "idRollover",
						'Dock', "box",
						'Visible', false,
						'Image', "UI/Common/row_shine_2.tga",
						'ImageFit', "stretch",
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "centers the texts",
						'HAlign', "center",
						'LayoutMethod', "HList",
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverHintGamepad', T{126202264713, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'IdNode', false,
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleFreeHomes()
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idFreeHomes",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{10453, --[[XTemplate Infobar Text]] "<FreeHomes>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverHintGamepad', T{126202264713, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'IdNode', false,
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleColonists("Homeless")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idHomeless",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{10454, --[[XTemplate Infobar Text]] "<Homeless>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverHintGamepad', T{126202264713, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'IdNode', false,
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleFreeWorkplaces()
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idFreeWork",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{579211823135, --[[XTemplate Infobar Text]] "<FreeWork>"},
							}),
							}),
						PlaceObj('XTemplateWindow', {
							'__class', "XButton",
							'RolloverHintGamepad', T{126202264713, --[[XTemplate Infobar RolloverHintGamepad]] "<ButtonA> Cycle stored resources<newline><DPad> Navigate <DPadDown> Close"},
							'IdNode', false,
							'HAlign', "center",
							'BorderColor', RGBA(0, 0, 0, 0),
							'Background', RGBA(0, 0, 0, 0),
							'MouseCursor', "UI/Cursors/Rollover.tga",
							'FocusedBorderColor', RGBA(0, 0, 0, 0),
							'FocusedBackground', RGBA(0, 0, 0, 0),
							'DisabledBorderColor', RGBA(0, 0, 0, 0),
							'OnPress', function (self, gamepad)
self.context:CycleColonists("Unemployed")
end,
							'RolloverBackground', RGBA(0, 0, 0, 0),
							'PressedBackground', RGBA(0, 0, 0, 0),
						}, {
							PlaceObj('XTemplateWindow', {
								'__class', "XText",
								'Id', "idUnemployed",
								'Padding', box(3, 4, 3, 4),
								'TextStyle', "Infobar",
								'Translate', true,
								'Text', T{895853208616, --[[XTemplate Infobar Text]] "<Unemployed>"},
							}),
							}),
						}),
					}),
				}),
			PlaceObj('XTemplateWindow', {
				'__class', "XImage",
				'Id', "idGamepadHint",
				'Padding', box(200, 25, 0, 0),
				'Dock', "box",
				'HAlign', "left",
				'VAlign', "top",
				'ImageScale', point(700, 700),
			}),
			}),
		}),
})

