-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

PlaceObj('XTemplate', {
	group = "InGame",
	id = "Infobar",
	PlaceObj('XTemplateWindow', {
		'__class', "Infobar",
		'ZOrder', 150,
		'FocusOnOpen', "",
	}, {
		PlaceObj('XTemplateWindow', {
			'__context', function (parent, context)  end,
			'__class', "XFrame",
			'Id', "idPad",
			'Margins', box(-274, 0, -274, 0),
			'Padding', box(274, 0, 274, 0),
			'HAlign', "center",
			'VAlign', "top",
			'MaxHeight', 30,
			'LayoutMethod', "HList",
			'HandleMouse', true,
			'Image', "UI/Common/bm_pad.tga",
			'FrameBox', box(274, 109, 274, 3),
			'SqueezeX', false,
			'FlipY', true,
		}, {
			PlaceObj('XTemplateWindow', {
				'__class', "XText",
				'RolloverTemplate', "Rollover",
				'RolloverAnchor', "bottom",
				'RolloverText', T{180475027963, --[[XTemplate Infobar RolloverText]] "<FundingRollover>"},
				'RolloverTitle', T{726290861385, --[[XTemplate Infobar RolloverTitle]] "Funding"},
				'Id', "idFunding",
				'Padding', box(2, 4, 2, 4),
				'MinWidth', 55,
				'TextFont', "OnScreenText",
				'TextColor', RGBA(255, 254, 171, 255),
				'RolloverTextColor', RGBA(255, 254, 171, 255),
				'Translate', true,
				'Text', T{325404562808, --[[XTemplate Infobar Text]] "<FundingText>"},
				'TextHAlign', "center",
				'TextVAlign', "center",
			}),
			PlaceObj('XTemplateWindow', {
				'__class', "XText",
				'RolloverTemplate', "Rollover",
				'RolloverAnchor', "bottom",
				'RolloverText', T{348303624799, --[[XTemplate Infobar RolloverText]] "<ResearchRollover>"},
				'RolloverTitle', T{711878045401, --[[XTemplate Infobar RolloverTitle]] "Research"},
				'Id', "idResearch",
				'Padding', box(2, 4, 2, 4),
				'MinWidth', 130,
				'TextFont', "OnScreenText",
				'TextColor', RGBA(255, 254, 171, 255),
				'RolloverTextColor', RGBA(255, 254, 171, 255),
				'Translate', true,
				'Text', T{212300384149, --[[XTemplate Infobar Text]] "<ResearchText>"},
				'TextHAlign', "center",
				'TextVAlign', "center",
			}),
			PlaceObj('XTemplateWindow', {
				'__class', "XText",
				'RolloverTemplate', "Rollover",
				'RolloverAnchor', "bottom",
				'RolloverText', T{942443234329, --[[XTemplate Infobar RolloverText]] "<GridResourcesRollover>"},
				'RolloverTitle', T{542251538468, --[[XTemplate Infobar RolloverTitle]] "Grid Resources"},
				'Id', "idGridResources",
				'Padding', box(2, 4, 2, 4),
				'MinWidth', 185,
				'TextFont', "OnScreenText",
				'TextColor', RGBA(255, 254, 171, 255),
				'RolloverTextColor', RGBA(255, 254, 171, 255),
				'Translate', true,
				'Text', T{374440054184, --[[XTemplate Infobar Text]] "<GridResourcesText>"},
				'TextHAlign', "center",
				'TextVAlign', "center",
			}),
			PlaceObj('XTemplateWindow', {
				'__class', "XContextWindow",
				'RolloverTemplate', "Rollover",
				'RolloverAnchor', "bottom",
				'RolloverText', T{953941296350, --[[XTemplate Infobar RolloverText]] "<BasicResourcesRollover>"},
				'RolloverTitle', T{736335290668, --[[XTemplate Infobar RolloverTitle]] "Basic Resources"},
				'RolloverHint', T{725007945580, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
				'Id', "idBasicResources",
				'MinWidth', 250,
			}, {
				PlaceObj('XTemplateWindow', {
					'comment', "centers the texts",
					'HAlign', "center",
					'LayoutMethod', "HList",
				}, {
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("Metals")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idMetals",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{290848825416, --[[XTemplate Infobar Text]] "<MetalsText>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("Concrete")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idConcrete",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{563905203540, --[[XTemplate Infobar Text]] "<ConcreteText>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("Food")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idFood",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{587907473693, --[[XTemplate Infobar Text]] "<FoodText>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("PreciousMetals")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idPreciousMetals",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{118276114882, --[[XTemplate Infobar Text]] "<PreciousMetalsText>"},
						}),
						}),
					}),
				}),
			PlaceObj('XTemplateWindow', {
				'__class', "XContextWindow",
				'RolloverTemplate', "Rollover",
				'RolloverAnchor', "bottom",
				'RolloverText', T{548027920915, --[[XTemplate Infobar RolloverText]] "<AdvancedResourcesRollover>"},
				'RolloverTitle', T{947912927019, --[[XTemplate Infobar RolloverTitle]] "Advanced Resources"},
				'RolloverHint', T{912394888157, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle stored resources"},
				'Id', "idAdvancedResources",
				'MinWidth', 250,
			}, {
				PlaceObj('XTemplateWindow', {
					'comment', "centers the texts",
					'HAlign', "center",
					'LayoutMethod', "HList",
				}, {
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("Polymers")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idPolymers",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{456271481390, --[[XTemplate Infobar Text]] "<PolymersText>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("Electronics")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idElectronics",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{312385745918, --[[XTemplate Infobar Text]] "<ElectronicsText>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("MachineParts")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idMachineParts",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{411476328157, --[[XTemplate Infobar Text]] "<MachinePartsText>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleResources("Fuel")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idFuel",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{771466895406, --[[XTemplate Infobar Text]] "<FuelText>"},
						}),
						}),
					}),
				}),
			PlaceObj('XTemplateWindow', {
				'__class', "XContextWindow",
				'RolloverTemplate', "Rollover",
				'RolloverAnchor', "bottom",
				'RolloverText', T{931628884394, --[[XTemplate Infobar RolloverText]] "<ColonistsRollover>"},
				'RolloverTitle', T{782298266613, --[[XTemplate Infobar RolloverTitle]] "Colonists<right><colonist(ColonistCount)>"},
				'RolloverHint', T{341358393315, --[[XTemplate Infobar RolloverHint]] "<left_click> Cycle"},
				'Id', "idColonists",
			}, {
				PlaceObj('XTemplateWindow', {
					'comment', "centers the texts",
					'HAlign', "center",
					'LayoutMethod', "HList",
				}, {
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleFreeHomes()
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idFreeHomes",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{10453, --[[XTemplate Infobar Text]] "<FreeHomes>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleColonists("Homeless")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idHomeless",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{10454, --[[XTemplate Infobar Text]] "<Homeless>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleFreeWorkplaces()
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idFreeWork",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{579211823135, --[[XTemplate Infobar Text]] "<FreeWork>"},
						}),
						}),
					PlaceObj('XTemplateWindow', {
						'__class', "XButton",
						'IdNode', false,
						'HAlign', "center",
						'BorderColor', RGBA(0, 0, 0, 0),
						'Background', RGBA(0, 0, 0, 0),
						'MouseCursor', "UI/Cursors/Rollover.tga",
						'FocusedBorderColor', RGBA(0, 0, 0, 0),
						'FocusedBackground', RGBA(0, 0, 0, 0),
						'DisabledBorderColor', RGBA(0, 0, 0, 0),
						'OnPress', function (self, gamepad)
self.context:CycleColonists("Unemployed")
end,
						'RolloverBackground', RGBA(0, 0, 0, 0),
						'PressedBackground', RGBA(0, 0, 0, 0),
					}, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
							'Id', "idUnemployed",
							'Padding', box(3, 4, 3, 4),
							'TextFont', "OnScreenText",
							'TextColor', RGBA(255, 254, 171, 255),
							'RolloverTextColor', RGBA(255, 254, 171, 255),
							'Translate', true,
							'Text', T{895853208616, --[[XTemplate Infobar Text]] "<Unemployed>"},
						}),
						}),
					}),
				}),
			}),
		}),
})

