-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

PlaceObj('XTemplate', {
	group = "InGame",
	id = "OverviewMapCurtains",
	PlaceObj('XTemplateWindow', {
		'__class', "OverviewMapCurtains",
		'LayoutMethod', "None",
		'HandleKeyboard', false,
		'ChildrenHandleMouse', false,
		'Translate', false,
		'FocusOnOpen', "",
	}, {
		PlaceObj('XTemplateWindow', {
			'__class', "XFrame",
			'Id', "idLeft",
			'Dock', "ignore",
			'Visible', false,
			'HandleKeyboard', false,
			'ChildrenHandleMouse', false,
			'EnableFX', false,
			'Image', "UI/Common/menu_pad_2_A.tga",
			'FrameBox', box(86, 0, 86, 0),
			'TileFrame', true,
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XFrame",
			'Id', "idRight",
			'Dock', "ignore",
			'Visible', false,
			'HandleKeyboard', false,
			'ChildrenHandleMouse', false,
			'EnableFX', false,
			'Image', "UI/Common/menu_pad_2_A.tga",
			'FrameBox', box(86, 0, 86, 0),
			'TileFrame', true,
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XFrame",
			'Id', "idTop",
			'Dock', "ignore",
			'Visible', false,
			'HandleKeyboard', false,
			'ChildrenHandleMouse', false,
			'EnableFX', false,
			'Image', "UI/Common/menu_pad_2_A.tga",
			'FrameBox', box(86, 0, 86, 0),
			'TileFrame', true,
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XFrame",
			'Id', "idBottom",
			'Dock', "ignore",
			'Visible', false,
			'HandleKeyboard', false,
			'ChildrenHandleMouse', false,
			'EnableFX', false,
			'Image', "UI/Common/menu_pad_2_A.tga",
			'FrameBox', box(86, 0, 86, 0),
			'TileFrame', true,
		}),
		}),
})

